/*
 * Generated By Spring Data JPA Entity Generator
 * @author Niroshan Mendis
 */

package bit.project.server.entity;

import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Lob;
import java.time.LocalDateTime;

@Data
@Entity
@NoArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
public class File {

    @Id
    private String id;
    @Lob
    private byte[] file;
    @Lob
    private byte[] thumbnail;
    private String filemimetype;
    private String thumbnailmimetype;
    private Long filesize;
    private String originalname;
    private LocalDateTime tocreation;
    private Boolean isused;


    public File(String id){
        this.id = id;
    }

    public File(String id, byte[] thumbnail, String thumbnailmimetype){
        this.id = id;
        this.thumbnail =thumbnail;
        this.thumbnailmimetype = thumbnailmimetype;
    }

    public File(String id, String filemimetype, byte[] file){
        this.id = id;
        this.file = file;
        this.filemimetype = filemimetype;
    }

    public File(String id, LocalDateTime tocreation){
        this.id = id;
        this.tocreation = tocreation;
    }

    public File(String id, Long filesize, String originalname, String filemimetype){
        this.id = id;
        this.filesize = filesize;
        this.originalname = originalname;
        this.filemimetype = filemimetype;
    }


}
