/*
 * Generated By Spring Data JPA Entity Generator
 * @author Niroshan Mendis
 */

package bit.project.server.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.Data;
import java.util.List;
import javax.persistence.*;
import java.time.LocalDateTime;

import lombok.NoArgsConstructor;

import javax.validation.constraints.Size;
import javax.validation.constraints.NotNull;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@Data
@Entity
@NoArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Notification{

    @Id
    private String id;

    @NotNull
    private LocalDateTime dosend;

    private LocalDateTime dodelivered;

    private LocalDateTime doread;

    @NotNull
    @JsonIgnore
    @ManyToOne(optional=false, fetch = FetchType.LAZY)
    private User user;

    @Lob
    @NotNull
    private String message;

    public Notification(String id){
        this.id = id;
    }

}
