/*
 * Generated By Spring Data JPA Entity Generator
 * @author Niroshan Mendis
 */

package bit.project.server.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import javax.validation.constraints.Size;
import java.util.List;

@Data
@Entity
@NoArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class Usecase{

    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    private Integer id;

    @Size(min=0, max=255, message="Maximum character count is 255")
    private String task;

    @ManyToOne(optional=false)
    @JsonIgnoreProperties({"usecaseList"})
    private Systemmodule systemmodule;

    @JsonIgnore
    @ManyToMany(mappedBy="usecaseList")
    private List<Role> roleList;

    public Usecase(Integer id){
        this.id = id;
    }
}
