/*
 * Generated By Spring Data JPA Entity Generator
 * @author Niroshan Mendis
 */

package bit.project.server.util.security;

public enum Tokenstatus {
    ACTIVE("Active"),
    DELETED("Deleted"),
    EXPIRED("Expired");

    public final String value;

    Tokenstatus(String value){
        this.value = value;
    }

    @Override
    public String toString() {
       return this.value;
    }
}
