/*
 * Generated By Spring Data JPA Entity Generator
 * @author Niroshan Mendis
 */

package bit.project.server.dao;

import bit.project.server.entity.Token;
import bit.project.server.util.jpasupplement.CriteriaQuerySupplement;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;

@RepositoryRestResource(exported=false)
public interface TokenDao extends JpaRepository<Token, String>, CriteriaQuerySupplement<Token>{

}
